### ISSUE TITLE
Tree Does not Expand

### ISSUE THREAD

**Issue by kitsonk** [wkeese/old-api-viewer#12] opened 2012-06-22 23:11 UTC
@dylans reports issues with Tree expansion with Firefox 14.

**Comment by wkeese** [comment] 2012-06-22 23:44
Hmm, FF14b8 is working fine for me, both on mac and Windows7.

From @dylans email:

```
Error: Invalid template: <div class="dijitTreeNode" role="presentation"
><div data-dojo-attach-point="rowNode" class="dijitTreeRow"
role="presentation" data-dojo-attach-event="onmouseenter:_onMouseEnter,
onmouseleave:_onMouseLeave, onclick:_onClick, ondblclick:_onDblClick"
><img src="${_blankGif}" alt="" data-dojo-attach-point="expandoNode"
class="dijitTreeExpando" role="presentation" /><span
data-dojo-attach-point="expandoNodeText" class="dijitExpandoText"
role="presentation" ></span ><span data-dojo-attach-point="contentNode"
class="dijitTreeContent" role="presentation"> <img src="${_blankGif}"
alt="" data-dojo-attach-point="iconNode" class="dijitIcon dijitTreeIcon"
role="presentation" /><span data-dojo-attach-point="labelNode"
class="dijitTreeLabel" role="treeitem" tabindex="-1"
aria-selected="false"
data-dojo-attach-event="onfocus:_onLabelFocus"></span> </span ></div>
<div data-dojo-attach-point="containerNode" class="dijitTreeContainer"
role="presentation" style="display: none;"></div> </div>
```

(no source for http://ajax.googleapis.com/ajax/libs/dojo/1.7/dojo/dojo.js)

**Comment by wkeese** [comment] 2012-07-10 02:13
Closing since I can't reproduce.

**Closed as completed by wkeese** 2012-07-10 02:13 UTC
Labels: bug
